on:
  workflow_dispatch: #temp
  # push:
  #   branches: [ "master" ]
name: BuildAndDeployWithSecrets
jobs:
  saveGamesBeforeDeploy:
    uses: ./.github/workflows/force-backup-of-savefiles.yml
    # build:
      # concurrency:
      #   group: "Start Bot"
      #   name: Build, Test, & Deploy Bot
      #   runs-on: ubuntu-latest
      #   steps:
        #   - name: executing remote ssh commands using password
        #     uses: appleboy/ssh-action@master
        #     env:
          #       AWS_KEY: ${{ secrets.IMG_AWS_KEY }}
          #       AWS_SECRET: ${{ secrets.IMG_AWS_SECRET }}
          #     with:
            #       host: ${{ secrets.SSH_HOST }}
            #       username: root
            #       password: ${{ secrets.SSH_PASSWORD }}
            #       port: 22
            #       script_stop: true
            #       envs: AWS_KEY, AWS_SECRET
            #       script: |
            #         echo "Pulling changes from GitHub..."
            #         cd /root/ti4bot/TI4_map_generator_bot
            #         git pull
            #         echo "Building docker image..."
            #         docker version
            #         docker build --build-arg BOT_KEY=$DISCORD_BOT_KEY --build-arg USER=$DISCORD_USER --build-arg SERVER=$DISCORD_SERVER --build-arg SERVER2=$DISCORD_SERVER2 --build-arg AWS_SECRET=$AWS_SECRET --build-arg AWS_KEY=$AWS_KEY -t tibot .
            #         echo "Restarting TIBot... giving 300 seconds to shutdown"
            #         docker stop $(docker ps -q) --time 300
            #         echo "Starting Container..."
            #         docker run -v /root/ti4bot/ti4bot_saves:/opt/STORAGE -d --restart unless-stopped tibot
            #         echo "Cleaning up docker stuff..."
            #         docker rm $(docker ps --filter status=exited -q) || true
            #         docker rmi -f $(docker images --filter "dangling=true" -q) || true
            #         echo "DONE!"
  saveGamesAfterDeploy:
    needs: saveGamesBeforeDeploy
    # needs: [build, saveGamesBeforeDeploy]
    uses: ./.github/workflows/force-backup-of-savefiles.yml
