on: workflow_dispatch
name: JavaDebug
concurrency:
  group: "Debug"
jobs:
  build:
    name: Run Debug Commands
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTINGER_SSH_HOST }}
        username: ${{ secrets.HOSTINGER_SSH_USER }}
        password: ${{ secrets.HOSTINGER_SSH_PASSWORD }}
        port: ${{ secrets.HOSTINGER_SSH_PORT }}
        script: |
          CONTAINER_ID=$(docker ps -q)
          docker exec -i $CONTAINER_ID bash -c '
            for pid in /proc/[0-9]*; do
              if grep -q "java" "$pid/comm" 2>/dev/null; then
            echo "${pid##*/}"
            export JAVA_PID="${pid##*/}"
              fi
            done
            echo $JAVA_PID
            jhsdb jmap --pid $JAVA_PID
          '
